#!/usr/bin/env bash

# Directory containing wallpapers
WALLPAPER_DIR="$HOME/wallpapers"

# Check if rofi is passing an argument
if [ -n "$1" ]; then
    # If an argument is passed, it is the selected image
    IMAGE="$1"
    
    # Check if the image still exists
    if [ -f "$IMAGE" ]; then
        # Run pywal to generate colors and set wallpaper
        # Assuming you're using wal to manage both. If you only want to set wallpaper, use feh or xwallpaper.
        wal -q -i "$IMAGE"

        # dwm needs to be restarted or reload its colors.
        # colors-wal-dwm.h is generated by wal, recompiling dwm might be required
        # or use xdotool, xsetroot, or a dwm patch to apply hot.
        # For this script we invoke wal.
    fi
    # Exit cleanly
    exit 0
fi

# Initial run: output entries for rofi to display
# We want to display image icons for rofi's block.
# Assuming the file names are safe enough or we just print the path.

find "$WALLPAPER_DIR" -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.webp" \) -print0 | while IFS= read -r -d '' file; do
    # Print the file path with the image icon attached
    echo -en "${file}\0icon\x1f${file}\n"
done
